services:
  frontend:
    build:
      context: ./frontend/customer-dashboard
    ports:
      - "3000:3000"

    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb+srv://username:password@cluster0.gjn7ccp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
